### ISSUE TITLE
French categories do not populate the input field when using Polylang plugin

### ISSUE THREAD

**Issue by LukaszJaro** [DanielFloeter/category-archives-block#2]
Hi,

I'm only able to populate English categories and not any other language, the alternative categories are not recognized at all. Also on the front end when switching the language they still remain as English. I'm using polylang for translations.

Potentially have to use this function pll_get_term($term_id, $slug); but I'm not sure how the code currently works so will take time for a fix unless you can figure it out quickly.

![image](https://user-images.githubusercontent.com/10998875/200094887-83ecb33f-6bab-46d3-a748-641dc447d146.png)

**Comment by DanielFloeter** [comment]
There are  thinks which are not so good but we use just WordPress APIs and don't want make our code less secure.
I would like to say, we couldn't give support for other plugins! 
Just correct and adapt some polylang traps and our widget will work.

Check your categories and set the "name" as the same as the "slug". Just have unique category "names". (Our widget and also the Gutenberg category selector works with the "name", not with the "slug".)

<img width="1496" alt="Bildschirmfoto 2022-11-05 um 23 58 50" src="https://user-images.githubusercontent.com/1297656/200144771-ee22fcee-37f8-41ad-8d00-2fd74154d8cf.png">


Second, for select the categories change the language on the page attributes to be in the right language context and have the right language categories available. Don't use the language selector on the top task bar.

<img width="1247" alt="Bildschirmfoto 2022-11-06 um 00 12 07" src="https://user-images.githubusercontent.com/1297656/200145727-34a4ae12-c922-4426-879d-068c9314b9f2.png">

**Comment by LukaszJaro** [comment]
Thank you for getting back! I should of clarified, this is for widgets.


![image](https://user-images.githubusercontent.com/10998875/200315534-cffbf12d-b8d8-4c87-b5fe-5260212e8586.png)

I'll have another look at the category name and slugs as well, thank you!
